#!/usr/bin/env python3
"""Mass translation script with extensive coverage."""

import polib


def get_massive_translations():
    """Return massive translation dictionary."""
    return {
        # Short entries from the list
        "Enter your organization's legal name.": "أدخل الاسم القانوني لمؤسستك.",
        "Apartment, suite, unit, etc. (optional).": "شقة، جناح، وحدة، إلخ. (اختياري).",
        "Enter your city.": "أدخل مدينتك.",
        "Tax ID (e.g., VAT, GST)": "الرقم الضريبي (مثل ضريبة القيمة المضافة، GST)",
        "VAT number validation is not supported for {}": "التحقق من رقم ضريبة القيمة المضافة غير مدعوم لـ {}",
        "You already have a page on that URL.": "لديك بالفعل صفحة على هذا الرابط.",
        "Selection contains various values": "يحتوي التحديد على قيم متنوعة",
        "Specific seat ID": "معرّف مقعد محدد",
        "Send vouchers via email": "إرسال القسائم عبر البريد الإلكتروني",
        "Your voucher for {event}": "قسيمتك لـ {event}",
        "Recipients": "المستلمون",
        "or": "أو",
        "Specific seat IDs": "معرّفات المقاعد المحددة",
        "{value} is not a valid email address.": "{value} ليس عنوان بريد إلكتروني صالحاً.",
        "Invalid value in row {number}.": "قيمة غير صالحة في الصف {number}.",
        "A fee of {old_price} was removed.": "تمت إزالة رسوم بقيمة {old_price}.",
        "Task management": "إدارة المهام",
        "Id": "المعرّف",
        "ZVT Terminal": "طرفية ZVT",
        "Home": "الرئيسية",
        "Talk": "محاضرة",
        "Access videos related to this event": "الوصول إلى الفيديوهات المتعلقة بهذا الحدث",
        "Videos": "الفيديوهات",
        "Geo coordinates": "الإحداثيات الجغرافية",
        "Geocoding data © OpenStreetMap": "بيانات الترميز الجغرافي © OpenStreetMap",
        "Failed to retrieve geo coordinates": "فشل في استرجاع الإحداثيات الجغرافية",
        "Retrieving geo coordinates …": "جاري استرجاع الإحداثيات الجغرافية ...",
        "Geo coordinates updated": "تم تحديث الإحداثيات الجغرافية",
        "Singular event or non-event shop": "حدث مفرد أو متجر بدون حدث",
        "Event series or time slot booking": "سلسلة أحداث أو حجز فترات زمنية",
        "That will cause %(count)s voucher to be unusable.": "سيؤدي ذلك إلى جعل %(count)s قسيمة غير قابلة للاستخدام.",
        "Percentage": "النسبة المئوية",
        "CANCELLATION REQUESTED": "تم طلب الإلغاء",
        "INVOICE NOT CANCELED": "الفاتورة غير ملغاة",
        "1 order": "طلب واحد",
        "Rotation (°)": "الدوران (°)",
        "Dynamic image": "صورة ديناميكية",
        "Break between slots": "فترة راحة بين الفترات الزمنية",
        "select all rows for batch-operation": "تحديد جميع الصفوف للعملية الجماعية",
        "Select all results on other pages as well": "تحديد جميع النتائج على الصفحات الأخرى أيضاً",
        "select row for batch-operation": "تحديد الصف للعملية الجماعية",
        "Enable or disable billing validation": "تمكين أو تعطيل التحقق من الفوترة",
        "{num} order": "{num} طلب",
        "Invalid value for billing validation!": "قيمة غير صالحة للتحقق من الفوترة!",
        "Your gift card code": "رمز بطاقة الهدايا الخاصة بك",
        "Video": "فيديو",
        "Talks": "المحاضرات",
        "Talks system": "نظام المحاضرات",
        "Video system": "نظام الفيديو",
        "Talk system": "نظام المحاضرات",
        "Create event for Talk system only not ready yet.": "إنشاء حدث لنظام المحاضرات فقط غير جاهز بعد.",
        "Both tickets and talk system": "نظام التذاكر والمحاضرات معاً",
        "Setting for Tickets system": "إعدادات نظام التذاكر",
        "Setting for Talk system": "إعدادات نظام المحاضرات",
        "One badge per page": "شارة واحدة لكل صفحة",
        "4 portrait A6 pages on one A4 page": "4 صفحات A6 عمودية على صفحة A4 واحدة",
        "8 landscape A7 pages on one A4 page": "8 صفحات A7 أفقية على صفحة A4 واحدة",
        "8 portrait A7 pages on one A4 page": "8 صفحات A7 عمودية على صفحة A4 واحدة",
        "Invalid IBAN/BIC": "IBAN/BIC غير صالح",
        "Automatic split to multiple orders not possible.": "التقسيم التلقائي إلى طلبات متعددة غير ممكن.",
        "Import currently running…": "الاستيراد قيد التشغيل حالياً...",
        "up to": "حتى",
        "Clear": "مسح",
        "Export bank transfer refunds": "تصدير استردادات التحويل البنكي",
        "SEPA XML": "SEPA XML",
        "Export SEPA xml": "تصدير SEPA xml",
        "Check-in log (all successful scans)": "سجل تسجيل الحضور (جميع عمليات المسح الناجحة)",
        "payment pending (except unapproved)": "الدفع معلق (باستثناء غير الموافق عليه)",
        "SocialAuth": "المصادقة الاجتماعية",
        "Social Login Setup": "إعداد تسجيل الدخول الاجتماعي",
        "Therefore, the complete callback URL should be": "لذلك، يجب أن يكون رابط الاستدعاء الكامل",
        "Follow the setup guide:": "اتبع دليل الإعداد:",
        "Set the callback URL to:": "اضبط رابط الاستدعاء إلى:",
        "II. GitHub OAuth Application": "II. تطبيق GitHub OAuth",
        "III. MediaWiki OAuth Application": "III. تطبيق MediaWiki OAuth",
        'Click "Propose new OAuth 2.0 client"': 'انقر على "اقتراح عميل OAuth 2.0 جديد"',
        "On the form enter": "في النموذج أدخل",
        'Set Oauth "callback" URL to:': 'اضبط رابط "callback" لـ OAuth إلى:',
        'Tick "Client is confidential"': 'حدد "العميل سري"',
        'Tick "Refresh token"': 'حدد "رمز التحديث"',
        "After Approval": "بعد الموافقة",
        "Blocked Seats": "المقاعد المحجوبة",
        "Unsold Seats": "المقاعد غير المباعة",
        "Potential Profits": "الأرباح المحتملة",
        "Blocked": "محجوب",
        "Seats not attributed to any specific product": "المقاعد غير المنسوبة لأي منتج محدد",
        "Open Layout Designer": "فتح مصمم التخطيط",
        "has errors": "به أخطاء",
        "Step %(current)s of %(total)s: %(label)s": "الخطوة %(current)s من %(total)s: %(label)s",
        "quantity": "الكمية",
        "We're applying this voucher to your cart...": "نحن نطبق هذه القسيمة على سلتك...",
        "W": "W",
        "General information, add products to your cart": "معلومات عامة، أضف منتجات إلى سلتك",
        "The current value of your gift card is %(value)s.": "القيمة الحالية لبطاقة الهدايا الخاصة بك هي %(value)s.",
        "Can't find your ticket?": "لا يمكنك العثور على تذكرتك؟",
        "to receive it.": "لاستلامها.",
        "Swahili": "السواحيلية",
        "User profile only": "ملف المستخدم فقط",
        "Kosovo": "كوسوفو",
        "or save as draft for now": "أو احفظها كمسودة الآن",
        
        # Additional common phrases
        "Loading...": "جاري التحميل...",
        "Please wait...": "يرجى الانتظار...",
        "Confirm": "تأكيد",
        "Warning": "تحذير",
        "Error": "خطأ",
        "Success": "نجاح",
        "Failed": "فشل",
        "Completed": "مكتمل",
        "Processing": "جاري المعالجة",
        "Pending": "قيد الانتظار",
        "Approved": "موافق عليه",
        "Rejected": "مرفوض",
        "Draft": "مسودة",
        "Published": "منشور",
        "Archived": "مؤرشف",
        "Active": "نشط",
        "Inactive": "غير نشط",
        "Enabled": "مفعّل",
        "Disabled": "معطّل",
        "Required": "مطلوب",
        "Optional": "اختياري",
        "Yes": "نعم",
        "No": "لا",
        "All": "الكل",
        "None": "لا شيء",
        "Select": "اختر",
        "Selected": "محدد",
        "Unselected": "غير محدد",
        "Apply": "تطبيق",
        "Reset": "إعادة تعيين",
        "Refresh": "تحديث",
        "Filter": "تصفية",
        "Sort": "ترتيب",
        "Export": "تصدير",
        "Import": "استيراد",
        "Download": "تحميل",
        "Upload": "رفع",
        "Print": "طباعة",
        "Share": "مشاركة",
        "Copy": "نسخ",
        "Cut": "قص",
        "Paste": "لصق",
        "Undo": "تراجع",
        "Redo": "إعادة",
        "Search": "بحث",
        "Find": "بحث",
        "Replace": "استبدال",
        "Next": "التالي",
        "Previous": "السابق",
        "First": "الأول",
        "Last": "الأخير",
        "Page": "الصفحة",
        "of": "من",
        "Total": "الإجمالي",
        "Count": "العدد",
        "Sum": "المجموع",
        "Average": "المتوسط",
        "Minimum": "الحد الأدنى",
        "Maximum": "الحد الأقصى",
        "From": "من",
        "To": "إلى",
        "Start": "البداية",
        "End": "النهاية",
        "Date": "التاريخ",
        "Time": "الوقت",
        "Today": "اليوم",
        "Yesterday": "أمس",
        "Tomorrow": "غداً",
        "Week": "أسبوع",
        "Month": "شهر",
        "Year": "سنة",
        "Hour": "ساعة",
        "Minute": "دقيقة",
        "Second": "ثانية",
        "Name": "الاسم",
        "Description": "الوصف",
        "Details": "التفاصيل",
        "Information": "معلومات",
        "Note": "ملاحظة",
        "Notes": "ملاحظات",
        "Comment": "تعليق",
        "Comments": "التعليقات",
        "Message": "الرسالة",
        "Messages": "الرسائل",
        "Notification": "إشعار",
        "Notifications": "الإشعارات",
        "Alert": "تنبيه",
        "Alerts": "التنبيهات",
        "Email": "البريد الإلكتروني",
        "Phone": "الهاتف",
        "Address": "العنوان",
        "City": "المدينة",
        "Country": "البلد",
        "Language": "اللغة",
        "Currency": "العملة",
        "Price": "السعر",
        "Amount": "المبلغ",
        "Quantity": "الكمية",
        "Discount": "الخصم",
        "Tax": "الضريبة",
        "Fee": "الرسوم",
        "Subtotal": "المجموع الفرعي",
        "Grand Total": "المجموع الكلي",
        "Payment": "الدفع",
        "Paid": "مدفوع",
        "Unpaid": "غير مدفوع",
        "Refund": "استرداد",
        "Refunded": "مُسترد",
        "Invoice": "الفاتورة",
        "Receipt": "الإيصال",
        "Order": "الطلب",
        "Orders": "الطلبات",
        "Product": "المنتج",
        "Products": "المنتجات",
        "Item": "العنصر",
        "Items": "العناصر",
        "Category": "الفئة",
        "Categories": "الفئات",
        "Tag": "الوسم",
        "Tags": "الوسوم",
        "Label": "التسمية",
        "Labels": "التسميات",
        "Status": "الحالة",
        "Type": "النوع",
        "Size": "الحجم",
        "Color": "اللون",
        "Image": "الصورة",
        "Images": "الصور",
        "File": "الملف",
        "Files": "الملفات",
        "Attachment": "المرفق",
        "Attachments": "المرفقات",
        "Link": "الرابط",
        "Links": "الروابط",
        "URL": "URL",
        "User": "المستخدم",
        "Users": "المستخدمون",
        "Account": "الحساب",
        "Profile": "الملف الشخصي",
        "Settings": "الإعدادات",
        "Preferences": "التفضيلات",
        "Configuration": "التكوين",
        "Options": "الخيارات",
        "Permission": "الصلاحية",
        "Permissions": "الصلاحيات",
        "Role": "الدور",
        "Roles": "الأدوار",
        "Group": "المجموعة",
        "Groups": "المجموعات",
        "Team": "الفريق",
        "Teams": "الفرق",
        "Member": "العضو",
        "Members": "الأعضاء",
        "Admin": "المدير",
        "Administrator": "المدير",
        "Owner": "المالك",
        "Manager": "المدير",
        "Editor": "المحرر",
        "Viewer": "المشاهد",
        "Guest": "ضيف",
        "Public": "عام",
        "Private": "خاص",
        "Shared": "مشترك",
        "Event": "الحدث",
        "Events": "الأحداث",
        "Organizer": "المنظم",
        "Organizers": "المنظمون",
        "Attendee": "الحاضر",
        "Attendees": "الحاضرون",
        "Ticket": "التذكرة",
        "Tickets": "التذاكر",
        "Registration": "التسجيل",
        "Check-in": "تسجيل الحضور",
        "Venue": "المكان",
        "Location": "الموقع",
        "Room": "القاعة",
        "Seat": "المقعد",
        "Seats": "المقاعد",
        "Voucher": "القسيمة",
        "Vouchers": "القسائم",
        "Gift card": "بطاقة الهدايا",
        "Quota": "الحصة",
        "Capacity": "السعة",
        "Available": "متاح",
        "Sold out": "نفدت الكمية",
        "Canceled": "ملغى",
        "Confirmed": "مؤكد",
        "Expired": "منتهي الصلاحية",
        "Valid": "صالح",
        "Invalid": "غير صالح",
        "Dashboard": "لوحة التحكم",
        "Overview": "نظرة عامة",
        "Report": "التقرير",
        "Reports": "التقارير",
        "Statistics": "الإحصائيات",
        "Analytics": "التحليلات",
        "Log": "السجل",
        "Logs": "السجلات",
        "History": "السجل",
        "Activity": "النشاط",
        "Help": "مساعدة",
        "Documentation": "التوثيق",
        "Support": "الدعم",
        "Contact": "اتصل بنا",
        "About": "حول",
        "Terms": "الشروط",
        "Privacy": "الخصوصية",
        "Legal": "قانوني",
        "Back": "رجوع",
        "Continue": "متابعة",
        "Skip": "تخطي",
        "Finish": "إنهاء",
        "Submit": "إرسال",
        "Send": "إرسال",
        "Save": "حفظ",
        "Cancel": "إلغاء",
        "Close": "إغلاق",
        "Delete": "حذف",
        "Remove": "إزالة",
        "Add": "إضافة",
        "Create": "إنشاء",
        "New": "جديد",
        "Edit": "تعديل",
        "Update": "تحديث",
        "Change": "تغيير",
        "Modify": "تعديل",
        "View": "عرض",
        "Show": "إظهار",
        "Hide": "إخفاء",
        "Open": "فتح",
        "OK": "موافق",
    }


def has_arabic(text):
    """Check if text contains Arabic characters."""
    if not text:
        return False
    return any('\u0600' <= c <= '\u06FF' for c in text)


def translate_po_file(filepath):
    """Translate a .po file with massive coverage."""
    print(f"\nTranslating {filepath}...")
    po = polib.pofile(filepath)
    
    translations = get_massive_translations()
    print(f"Translation dictionary size: {len(translations)}")
    
    untranslated_before = len(po.untranslated_entries())
    print(f"Untranslated entries: {untranslated_before}")
    
    if untranslated_before == 0:
        print("No untranslated entries!")
        return 0
    
    translated_count = 0
    for entry in po.untranslated_entries():
        if not entry.msgid or not entry.msgid.strip():
            continue
        
        # Try exact match
        if entry.msgid in translations:
            entry.msgstr = translations[entry.msgid]
            translated_count += 1
        else:
            # Try case-insensitive match
            msgid_lower = entry.msgid.lower()
            for key, value in translations.items():
                if key.lower() == msgid_lower:
                    entry.msgstr = value
                    translated_count += 1
                    break
    
    if translated_count > 0:
        print(f"Translated {translated_count} entries")
        po.save(filepath)
        
        # Verify
        po_verify = polib.pofile(filepath)
        untranslated_after = len(po_verify.untranslated_entries())
        print(f"Remaining untranslated: {untranslated_after}")
        return translated_count
    else:
        print("No new translations applied")
        return 0


# Main execution
if __name__ == "__main__":
    count1 = translate_po_file('app/eventyay/locale/ar/LC_MESSAGES/django.po')
    count2 = translate_po_file('app/eventyay/locale/ar/LC_MESSAGES/djangojs.po')
    
    total = count1 + count2
    print(f"\n{'='*70}")
    print(f"TOTAL TRANSLATIONS APPLIED: {total}")
    print(f"{'='*70}")
