# Generated by Django 5.2.15 on 2026-08-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_alter_talkquestion_variant_add_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_thumbnail_list',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
